/**
 * Generates shared/pricing-vectors.json — the cross-repo pricing contract.
 *
 * Run: `npm run gen:pricing-vectors`
 *
 * The output is the SINGLE source of expected estimate outputs, checked into
 * BOTH maineclean.co and Bright-Space. Each repo's pricing test asserts its
 * engine reproduces every row here. Regenerate this ONLY when you have
 * deliberately changed the rate card in @shared/pricing (and mirrored it in
 * Bright-Space's backend/modules/booking/pricing.py) — a diff here in a PR is
 * a red flag that pricing moved and both engines + this file must agree.
 */
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { computeEstimate, type EstimateInputs } from "../shared/pricing";

const SQFTS = [500, 800, 1200, 1500, 1800, 2400, 3000, 3600, 5000, 6000];
const BATHS = [1, 1.5, 2, 2.5, 3, 4.5];
const CLEAN_TYPES = ["standard", "deep"] as const;
const FREQS = ["weekly", "biweekly", "monthly", "one-time"] as const;
const CONDS = ["maintenance", "moderate", "heavy"] as const;
const PETS = ["none", "some", "heavy"] as const;

type Vector = { input: EstimateInputs; expected: { min: number; max: number; mid: number } };

// The ORIGINAL inline formula, verbatim from the pre-refactor client engine.
// Kept ONLY to prove computeEstimate is behavior-identical before we bake its
// output into the contract — a refactor of the live pricing path must not
// change a single quote. Delete once you trust the shared module.
function oldEstimate(i: EstimateInputs): { min: number; max: number } {
  const RATE = 60;
  const minJob = i.cleanType === "standard" ? 130 : 225;
  const sf = i.sqft;
  const sqftUnits = sf <= 1500 ? sf / 680 : sf <= 3000 ? 1500 / 680 + (sf - 1500) / 1050 : 1500 / 680 + 1500 / 1050 + (sf - 3000) / 1400;
  const bathAdj = Math.max(0, (i.bathrooms - 1) * 0.40);
  const condUnits: Record<string, number> = { maintenance: 0, moderate: 0.50, heavy: 1.00 };
  const petUnits: Record<string, number> = { none: 0, some: 0.30, heavy: 0.60 };
  const deepMult = i.cleanType === "deep" ? (sf <= 1200 ? 1.60 : sf <= 2000 ? 1.65 : sf <= 3000 ? 1.75 : 1.80) : 1.0;
  const labor = (sqftUnits + bathAdj + condUnits[i.condition ?? "maintenance"] + petUnits[i.petHair ?? "none"]) * deepMult;
  const freqMap: Record<string, number> = { weekly: 0.85, biweekly: 1.0, monthly: 1.15, "one-time": 1.50 };
  const raw = labor * freqMap[i.frequency ?? "one-time"] * RATE;
  const final = Math.max(minJob, Math.round(raw / 5) * 5);
  return { min: Math.round((final * 0.96) / 5) * 5, max: Math.round((final * 1.04) / 5) * 5 };
}

const vectors: Vector[] = [];
// Full grid on the levers that interact non-linearly (sqft × baths × cleanType),
// then sweep freq/condition/pet at a representative mid-size home so the file
// covers every discrete factor without exploding to tens of thousands of rows.
for (const sqft of SQFTS) {
  for (const bathrooms of BATHS) {
    for (const cleanType of CLEAN_TYPES) {
      const input: EstimateInputs = { sqft, bathrooms, cleanType, frequency: "one-time", condition: "maintenance", petHair: "none" };
      const e = computeEstimate(input);
      assertEquiv(input, e);
      vectors.push({ input, expected: { min: e.min, max: e.max, mid: e.mid } });
    }
  }
}
for (const frequency of FREQS) {
  for (const condition of CONDS) {
    for (const petHair of PETS) {
      const input: EstimateInputs = { sqft: 1800, bathrooms: 2, cleanType: "standard", frequency, condition, petHair };
      const e = computeEstimate(input);
      assertEquiv(input, e);
      vectors.push({ input, expected: { min: e.min, max: e.max, mid: e.mid } });
    }
  }
}

function assertEquiv(input: EstimateInputs, e: { min: number; max: number }) {
  const o = oldEstimate(input);
  if (o.min !== e.min || o.max !== e.max) {
    throw new Error(
      `PRICING DRIFT: computeEstimate diverged from the original formula for ` +
      `${JSON.stringify(input)} — old $${o.min}-$${o.max} vs new $${e.min}-$${e.max}. ` +
      `Refactor must preserve every quote.`,
    );
  }
}

const out = { _comment: "Cross-repo pricing contract — generated by scripts/gen-pricing-vectors.ts. Do not hand-edit.", vectors };
const dest = join(dirname(fileURLToPath(import.meta.url)), "..", "shared", "pricing-vectors.json");
writeFileSync(dest, JSON.stringify(out, null, 2) + "\n");
console.log(`Wrote ${vectors.length} vectors to ${dest}`);
